# generated by datamodel-codegen:
#   filename:  output_schema.json
#   timestamp: 2026-08-18T18:12:36+00:00

from __future__ import annotations

from enum import Enum
from typing import Literal

from pydantic import (
    AwareDatetime,
    BaseModel,
    ConfigDict,
    Field,
    RootModel,
    confloat,
    conint,
    constr,
)


class Disposition(Enum):
    approved = 'approved'
    escalated = 'escalated'


class Documents(BaseModel):
    pass


class EvidenceItem(RootModel[constr(pattern=r'\S', min_length=1)]):
    root: constr(pattern=r'\S', min_length=1)


class Check(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    evidence: list[EvidenceItem] = Field(..., min_length=1)
    hard_fail: bool
    id: constr(pattern=r'\S', min_length=1)
    label: constr(pattern=r'\S', min_length=1)
    passed: bool
    weight: confloat(ge=0.0, le=100.0)


class Route(Enum):
    auto_approve = 'auto_approve'
    partial_approve_with_hold = 'partial_approve_with_hold'
    human_review = 'human_review'


class RouteEvidenceItem(RootModel[constr(pattern=r'\S', min_length=1)]):
    root: constr(pattern=r'\S', min_length=1)


class Gate(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    checks: list[Check] = Field(
        ...,
        description='Candidate-defined deterministic checks. Check IDs must be unique, weights must total 100, and score must equal the weights of passed checks.',
        min_length=1,
    )
    eligible_for_stp: bool
    hard_failure: bool
    route: Route
    route_evidence: list[RouteEvidenceItem] = Field(..., min_length=1)
    score: confloat(ge=0.0, le=100.0)
    threshold: confloat(ge=0.0, le=100.0)


class PolicyCitation(RootModel[constr(pattern=r'\S', min_length=1)]):
    root: constr(pattern=r'\S', min_length=1)


class Status(Enum):
    approved = 'approved'
    partially_approved_items_held = 'partially_approved_items_held'
    needs_human_review = 'needs_human_review'


class WritebackPreview(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    approved_amount: confloat(ge=0.0, multiple_of=0.01)
    automation_quality_score: conint(ge=0, le=100)
    case_number: conint(ge=1, le=20)
    claim_id: constr(pattern=r'\S', min_length=1)
    claim_type: Literal['occupancy_exit_protection']
    claimed_amount: confloat(ge=0.0, multiple_of=0.01)
    covered_amount: confloat(ge=0.0, multiple_of=0.01)
    destination: constr(pattern=r'\S', min_length=1)
    excluded_amount: confloat(ge=0.0, multiple_of=0.01)
    external_write_performed: Literal[False]
    held_amount: confloat(ge=0.0, multiple_of=0.01)
    payment_action: Literal['preview_only']
    policy_citations: list[PolicyCitation] = Field(..., min_length=1)
    policy_limit: confloat(ge=0.0, multiple_of=0.01)
    route: Route
    ruleset: constr(pattern=r'\S', min_length=1)
    simulated: Literal[True]
    status: Status


class Status1(Enum):
    provided = 'provided'
    not_applicable = 'not_applicable'
    missing = 'missing'
    unclear = 'unclear'


class ChecklistItem(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    detail: constr(pattern=r'\S', min_length=1)
    evidence: constr(pattern=r'\S', min_length=1)
    item: constr(pattern=r'\S', min_length=1)
    source_page: conint(ge=1)
    status: Status1


class Citation(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    clause_id: constr(pattern=r'\S', min_length=1)
    heading: constr(pattern=r'\S', min_length=1)
    quote: constr(pattern=r'\S', min_length=1)
    source_page: conint(ge=1)


class ConflictValue(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    evidence: constr(pattern=r'\S', min_length=1)
    source_document: constr(pattern=r'\S', min_length=1)
    source_page: conint(ge=1)
    value: constr(pattern=r'\S', min_length=1)


class Status2(Enum):
    covered = 'covered'
    partially_covered = 'partially_covered'
    excluded = 'excluded'
    needs_review = 'needs_review'


class DocumentType(Enum):
    loss_notice_and_record_index = 'loss_notice_and_record_index'
    tenancy_financial_journal = 'tenancy_financial_journal'
    restoration_cost_register = 'restoration_cost_register'
    premises_condition_log = 'premises_condition_log'
    covered_tenancy_certificate = 'covered_tenancy_certificate'


class EvidenceType(Enum):
    account_ledger = 'account_ledger'
    charges_statement = 'charges_statement'
    condition_record = 'condition_record'
    protection_agreement = 'protection_agreement'
    invoice = 'invoice'
    work_order = 'work_order'
    component_record = 'component_record'
    temporary_arrangement_receipt = 'temporary_arrangement_receipt'
    completion_record = 'completion_record'
    photograph = 'photograph'
    payment_credit_or_recovery = 'payment_credit_or_recovery'
    other = 'other'


class Status3(Enum):
    provided = 'provided'
    attached = 'attached'
    not_provided = 'not_provided'
    estimate_only = 'estimate_only'
    missing_detail = 'missing_detail'
    not_applicable = 'not_applicable'
    unclear = 'unclear'


class EvidenceAssertion(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    applies_to: list[constr(pattern=r'\S', min_length=1)]
    evidence: constr(pattern=r'\S', min_length=1)
    evidence_type: EvidenceType
    label: constr(pattern=r'\S', min_length=1)
    reference: constr(pattern=r'\S', min_length=1) | None
    source_page: conint(ge=1)
    status: Status3


class EntryType(Enum):
    charge = 'charge'
    payment = 'payment'
    credit = 'credit'
    recovery = 'recovery'
    reversal = 'reversal'
    adjustment = 'adjustment'


class LedgerEntry(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    charge_amount: confloat(ge=0.0, multiple_of=0.01)
    credit_amount: confloat(ge=0.0, multiple_of=0.01)
    description: constr(pattern=r'\S', min_length=1)
    entry_date: constr(pattern=r'\S', min_length=1)
    entry_type: EntryType
    evidence: constr(pattern=r'\S', min_length=1)
    running_balance: confloat(multiple_of=0.01) | None
    source_page: conint(ge=1)


class Kind(Enum):
    betterment = 'betterment'
    depreciation = 'depreciation'
    duplicate = 'duplicate'
    ledger_reversal = 'ledger_reversal'
    payment_credit_or_recovery = 'payment_credit_or_recovery'
    missing_proof = 'missing_proof'
    wear_or_pre_existing = 'wear_or_pre_existing'
    noncovered_fee = 'noncovered_fee'
    time_cutoff = 'time_cutoff'
    other = 'other'


class LineAdjustment(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    amount: confloat(ge=0.0, multiple_of=0.01)
    detail: constr(pattern=r'\S', min_length=1)
    evidence: constr(pattern=r'\S', min_length=1)
    kind: Kind
    source_page: conint(ge=1)


class ReconciliationEvidenceItem(RootModel[constr(pattern=r'\S', min_length=1)]):
    root: constr(pattern=r'\S', min_length=1)


class MathAudit(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    allocation_order: constr(pattern=r'\S', min_length=1)
    approved_lines_total: confloat(ge=0.0, multiple_of=0.01)
    cap_method: constr(pattern=r'\S', min_length=1)
    case_identity_passed: bool
    currency: Literal['USD']
    line_identity_passed: bool
    preliminary_payable_amount: confloat(ge=0.0, multiple_of=0.01)
    reconciliation_evidence: list[ReconciliationEvidenceItem] = Field(..., min_length=1)
    rounding_mode: Literal['ROUND_HALF_UP']


class CostSource(Enum):
    provider = 'provider'
    estimated = 'estimated'
    not_available = 'not_available'


class MoneyMention(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    amount: confloat(ge=0.0, multiple_of=0.01)
    evidence: constr(pattern=r'\S', min_length=1)
    label: constr(pattern=r'\S', min_length=1)
    source_page: conint(ge=1)


class PolicyClause(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    clause_id: constr(pattern=r'\S', min_length=1)
    evidence: constr(pattern=r'\S', min_length=1)
    heading: constr(pattern=r'\S', min_length=1)
    source_page: conint(ge=1)
    text: constr(pattern=r'\S', min_length=1)


class PolicyExtraction(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    clauses: list[PolicyClause] = Field(..., min_length=1)
    policy_form: Literal['OEP-2027-SYN']
    warnings: list[constr(pattern=r'\S', min_length=1)]


class PolicyMatch(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    clause_id: constr(pattern=r'\S', min_length=1)
    heading: constr(pattern=r'\S', min_length=1)
    lexical_boost: float
    method: constr(pattern=r'\S', min_length=1)
    query: constr(pattern=r'\S', min_length=1)
    score: float
    similarity: confloat(ge=0.0, le=1.0)
    source_page: conint(ge=1)
    text: constr(pattern=r'\S', min_length=1)


class RenderedPage(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    evidence_anchor: constr(pattern=r'\S', min_length=1)
    extracted_text: constr(pattern=r'\S', min_length=1)
    image_artifact: constr(pattern=r'\S', min_length=1) | None = None
    page_number: conint(ge=1)
    text_artifact: constr(pattern=r'\S', min_length=1) | None = None


class Outcome(Enum):
    applied = 'applied'
    passed = 'passed'
    held = 'held'
    excluded = 'excluded'
    informational = 'informational'


class RuleTraceStep(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    adjustment_amount: confloat(multiple_of=0.01)
    detail: constr(pattern=r'\S', min_length=1)
    evidence: list[EvidenceItem] = Field(..., min_length=1)
    input_amount: confloat(ge=0.0, multiple_of=0.01)
    outcome: Outcome
    output_amount: confloat(ge=0.0, multiple_of=0.01)
    rule_id: constr(pattern=r'\S', min_length=1)


class ResolutionStatus(Enum):
    resolved = 'resolved'
    unresolved = 'unresolved'


class SourceConflict(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    evidence: list[EvidenceItem] = Field(..., min_length=1)
    field: constr(pattern=r'\S', min_length=1)
    resolution: constr(pattern=r'\S', min_length=1)
    resolution_status: ResolutionStatus
    values: list[ConflictValue] = Field(..., min_length=2)


class SourceFact(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    evidence: constr(pattern=r'\S', min_length=1)
    field: constr(pattern=r'\S', min_length=1)
    source_page: conint(ge=1)
    value: constr(pattern=r'\S', min_length=1)


class DocumentationStatus(Enum):
    sufficient = 'sufficient'
    estimate_only = 'estimate_only'
    missing = 'missing'
    not_applicable = 'not_applicable'
    unclear = 'unclear'


class SubmittedLine(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    adjustments: list[LineAdjustment]
    amount: confloat(ge=0.0, multiple_of=0.01)
    category_hint: constr(pattern=r'\S', min_length=1)
    description: constr(pattern=r'\S', min_length=1)
    documentation_status: DocumentationStatus
    evidence: constr(pattern=r'\S', min_length=1)
    first_use_date: constr(pattern=r'\S', min_length=1) | None
    life_used_months: conint(ge=0) | None
    protected_period_end: constr(pattern=r'\S', min_length=1) | None
    protected_period_start: constr(pattern=r'\S', min_length=1) | None
    reference: constr(pattern=r'\S', min_length=1) | None
    source_classification: constr(pattern=r'\S', min_length=1)
    source_index: conint(ge=0)
    source_page: conint(ge=1)
    stated_rate: confloat(ge=0.0, multiple_of=0.01) | None
    useful_life_months: conint(ge=1) | None


class TokenUsage(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    cached_input_tokens: conint(ge=0)
    input_tokens: conint(ge=0)
    output_tokens: conint(ge=0)
    total_tokens: conint(ge=0)


class Status4(Enum):
    completed = 'completed'
    recovered_after_retry = 'recovered_after_retry'


class ToolCall(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    attempt_count: conint(ge=1)
    duration_ms: conint(ge=0)
    evidence: list[EvidenceItem] = Field(..., min_length=1)
    output_summary: constr(pattern=r'\S', min_length=1)
    purpose: constr(pattern=r'\S', min_length=1)
    status: Status4
    tool: constr(pattern=r'\S', min_length=1)


class DecisionLine(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    approved_amount: confloat(ge=0.0, multiple_of=0.01)
    category: constr(pattern=r'\S', min_length=1)
    citations: list[Citation] = Field(..., min_length=1)
    claimed_amount: confloat(ge=0.0, multiple_of=0.01)
    covered_amount: confloat(ge=0.0, multiple_of=0.01)
    description: constr(pattern=r'\S', min_length=1)
    excluded_amount: confloat(ge=0.0, multiple_of=0.01)
    held_amount: confloat(ge=0.0, multiple_of=0.01)
    rationale: constr(pattern=r'\S', min_length=1)
    rule_trace: list[RuleTraceStep] | None = Field(None, min_length=1)
    source_document: constr(pattern=r'\S', min_length=1)
    source_evidence: constr(pattern=r'\S', min_length=1)
    source_index: conint(ge=0)
    source_page: conint(ge=1)
    status: Status2


class DocumentExtraction(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    agreement_id: constr(pattern=r'\S', min_length=1) | None
    checklist_items: list[ChecklistItem]
    claim_id: constr(pattern=r'\S', min_length=1) | None
    claim_type: constr(pattern=r'\S', min_length=1) | None
    claimed_total: confloat(ge=0.0, multiple_of=0.01) | None
    document_type: DocumentType
    ending_balance: confloat(multiple_of=0.01) | None
    event_date: constr(pattern=r'\S', min_length=1) | None
    evidence_assertions: list[EvidenceAssertion]
    facts: list[SourceFact] = Field(..., min_length=1)
    ledger_entries: list[LedgerEntry]
    limit_mentions: list[MoneyMention]
    participant_name: constr(pattern=r'\S', min_length=1) | None
    policy_form: constr(pattern=r'\S', min_length=1) | None
    protected_location: constr(pattern=r'\S', min_length=1) | None
    protection_end: constr(pattern=r'\S', min_length=1) | None
    protection_start: constr(pattern=r'\S', min_length=1) | None
    statement_date: constr(pattern=r'\S', min_length=1) | None
    submitted_lines: list[SubmittedLine]
    warnings: list[constr(pattern=r'\S', min_length=1)]


class ModelCall(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    attempt_count: conint(ge=1)
    cost_source: CostSource
    cost_usd: confloat(ge=0.0) | None
    duration_ms: conint(ge=0)
    provider: constr(pattern=r'\S', min_length=1)
    purpose: constr(pattern=r'\S', min_length=1)
    requested_model: constr(pattern=r'\S', min_length=1)
    response_id: constr(pattern=r'\S', min_length=1) | None
    routed_model: constr(pattern=r'\S', min_length=1)
    routed_provider: constr(pattern=r'\S', min_length=1)
    stored_by_provider: bool
    usage: TokenUsage


class PolicyAudit(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    extraction: PolicyExtraction | None = None
    filename: constr(pattern=r'\S', min_length=1)
    page_count: conint(ge=1)
    provenance: constr(pattern=r'\S', min_length=1)
    rendered_pages: list[RenderedPage] | None = Field(None, min_length=1)
    sha256: constr(pattern=r'^[0-9a-f]{64}$')


class DocumentAudit(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    document_type: DocumentType
    extraction: DocumentExtraction | None = None
    filename: constr(pattern=r'\S', min_length=1)
    page_count: conint(ge=1)
    provenance: constr(pattern=r'\S', min_length=1)
    rendered_pages: list[RenderedPage] | None = Field(None, min_length=1)
    sha256: constr(pattern=r'^[0-9a-f]{64}$')


class Result(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    approved_amount: confloat(ge=0.0, multiple_of=0.01)
    case_number: conint(ge=1, le=20)
    claim_id: constr(pattern=r'^OEP-27-[0-9]{4}$')
    claim_type: Literal['occupancy_exit_protection']
    claimed_amount: confloat(ge=0.0, multiple_of=0.01)
    completed_at: AwareDatetime
    covered_amount: confloat(ge=0.0, multiple_of=0.01)
    decision_lines: list[DecisionLine] = Field(..., min_length=1)
    disposition: Disposition
    documents: list[DocumentAudit] | Documents = Field(..., max_length=4, min_length=4)
    excluded_amount: confloat(ge=0.0, multiple_of=0.01)
    gate: Gate
    held_amount: confloat(ge=0.0, multiple_of=0.01)
    math_audit: MathAudit
    model_calls: list[ModelCall]
    outcome_summary: constr(pattern=r'\S', min_length=1)
    policy_audit: PolicyAudit
    policy_form: Literal['OEP-2027-SYN']
    policy_limit: confloat(ge=0.0, multiple_of=0.01)
    retrieved_policy: list[PolicyMatch] = Field(..., min_length=1)
    run_id: constr(pattern=r'\S', min_length=1)
    source_conflicts: list[SourceConflict]
    tool_calls: list[ToolCall]
    warnings: list[constr(pattern=r'\S', min_length=1)]
    writeback_preview: WritebackPreview


class AlderquillOccupancyExitProtectionV2Result(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    results: list[Result] = Field(..., max_length=10, min_length=1)
